Fix: (Setup Continuous Integration & Quality Assurance pipeline): - Resoliving coverage badge congiguration conflicts

diff --git a/.github/workflows/coverage.js.yml b/.github/workflows/coverage.js.yml
--- a/.github/workflows/coverage.js.yml
+++ b/.github/workflows/coverage.js.yml
@@ -1,27 +1,42 @@
-name: Coverage
-
-on:
-  push:
-    branches: [develop, ch-setup-integrations-18]
-  pull_request:
-    branches: [ develop, ch-setup-integrations-18]
+name: "Coverage"
+on: [pull_request, push]
 
 jobs:
-  coverage:
-    name: coverage
+  check_pr:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ matrix.node-version }}
-          cache: "npm"
-      - run: npm i
-      - uses: paambaati/codeclimate-action@v2.5.0
-        env:
-          CI: "true"
-          CC_TEST_REPORTER_ID: 321ee8fd219aad6def946d2acd307cdaff1b215d53ae48dfea5c7ebce2ef875c
-        with:
-          debug: true
-          coverageCommand: npm run coverage
+    - name: checkout code
+      uses: actions/checkout@v3
+
+    - name: install dependencies
+      run: npm install
+
+    - name: build typescript
+      run: npm run build
+
+    - name: run tests and instrument coverage
+      run: npm run coverage
+
+    - name: check for unformatted sources
+      run: |
+        npm run format:check \
+        || (echo "##[error] found unformatted files. please 'npm run format'" \
+                 "and check in all changes" \
+            && exit 1)
+
+    - name: check for uncommitted changes
+      # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
+      run: |
+        git diff --exit-code --stat -- . ':!node_modules' \
+        || (echo "##[error] found changed files after build. please 'npm run build'" \
+                 "and check in all changes" \
+            && exit 1)
+
+    - name: publish code coverage to code-climate (duh)
+      uses: paambaati/codeclimate-action@v3.0.0
+      env:
+        CC_TEST_REPORTER_ID: 321ee8fd219aad6def946d2acd307cdaff1b215d53ae48dfea5c7ebce2ef875c
+      with:
+        coverageCommand: npm run coverage
+        debug: true
+      if: ${{ github.event_name == 'push' }}
